name: Building the Java project with customscript
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Build-Java-Project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build project with custom script and Xvfb
        run: |
          apt update -y
          apt -y install xvfb curl zip unzip xsltproc
          export DISPLAY=":99.0"
          export AUDIODEV=null
          xvfb-run :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          curl -s "https://get.sdkman.io" | bash
          source "/root/.sdkman/bin/sdkman-init.sh"
          sdk env install
          sdk env use
          chmod a+x "$HOME/.sdkman/bin/sdkman-init.sh"
          #/root/.sdkman/candidates/maven/current/mvn -B package -DskipTests=true --file pom.xml
          chmod +x ./build.sh
          ./build.sh a
